version: "3.9"
services:
  site:
    image: node:lts-bullseye-slim
    container_name: sultanimmubin
    working_dir: /sultanimmubin
    ports:
      - 3000:3000
    volumes:
      - ".:/sultanimmubin"
    command: >
      sh -c
      "
      npm install
      && npm run dev &
      tail -f /dev/null
      "
      
